[tox]
min_version = 4.0
env_list = py39, py310, py311, py312, numpy1, numpy2, quality

[testenv]
deps =
    pytest
    coverage
    hypothesis
    numpy>=1.24,<3
commands =
    coverage run -m pytest {posargs}
    coverage report --include=tiny_ecdh/* --fail-under=95

[testenv:numpy1]
base_python = py311
deps =
    pytest
    coverage
    hypothesis
    numpy>=1.24,<2
commands =
    coverage run -m pytest {posargs}
    coverage report --include=tiny_ecdh/* --fail-under=95

[testenv:numpy2]
base_python = py311
deps =
    pytest
    coverage
    hypothesis
    numpy>=2,<3
commands =
    coverage run -m pytest {posargs}
    coverage report --include=tiny_ecdh/* --fail-under=95

[testenv:quality]
skip_install = true
deps =
    build
    mypy
    ruff
    twine
commands =
    ruff check .
    ruff format --check .
    mypy --strict tiny_ecdh
    python -m build
    twine check --strict dist/*
